services:
  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002/manager
      KONG_ADMIN_GUI_PATH: "/"
    volumes:
      - ./kong.yml:/kong/kong.yml
    ports:
      - '8000:8000'  # Proxy Port
      - '8001:8001'  # Admin API
      - '8002:8002'  # Manager GUI
  hey:
    image: demisto/rakyll-hey:1.0.0.108484
    depends_on: 
      - kong
    command: ["hey", "http://kong:8000/example"]
