version: '3'
services:
  hey:
    image: rakyll/hey
    volumes:
      - ./body.json:/body.json
    command:
      - "-n"
      - "100"
      - "-c"
      - "10"
      - "-m"
      - "POST"
      - "-H"
      - "Content-Type: application/json"
      - "-H"
      - "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDk1NzEyNzcsImlhdCI6MTc0OTU2NzY3NywidXNlcl9pZCI6IjhiZjBmOWZlLTNiOTQtNDJjOC1iMTM0LTY3YTYyMjI3NzFkMyJ9.NQb9C6N2TFt-QnKhEbn_ipMqAHIMIV05WNnVzyP4ZHs"
      - "-D"
      - "/body.json"
      - "http://51.250.38.29:8080/content/text"
