name: Run hey against 1.1.1.1

on: 
  push:
    branches: [ main ] 

jobs:
  hey:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run hey against 1.1.1.1
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose-custom.yml"
